[package]
name = "aedat_reader"
version = "0.1.0"
authors = ["Anthony Beninati <abeninati01@manhattan.edu>"]
edition = "2021"

[dependencies]
image = "0.25.1"
clap = "4.5.6"
opencv = "0.92.0"
natord = "1.0.9"
